stages:
  - build_docker_image_prod

build_docker_image_prod:
  only:
    refs:
      - main
  stage: build_docker_image_prod
  interruptible: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${IMAGE_REPOSITORY}\":{\"auth\":\"$(printf "%s:%s" "${ROBOT_USER}" "${HARBOR_ROBOT_KEY_BUILD_BACKEND}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $IMAGE_REPOSITORY/cci-tools/psono-helm-secret-helper:latest \
        --destination $IMAGE_REPOSITORY/cci-tools/psono-helm-secret-helper:$CI_COMMIT_SHORT_SHA

